// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlMv3goYEt4GKE8hd4bRdHaagseyE3TE',
    appId: '1:517365773717:android:495224130bdb993d06329c',
    messagingSenderId: '517365773717',
    projectId: 'proyectoutem-d83cb',
    storageBucket: 'proyectoutem-d83cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-h5IeSAWkCVz07V5iUqP4uRJD88W_5bQ',
    appId: '1:517365773717:ios:810fa1a7503958d706329c',
    messagingSenderId: '517365773717',
    projectId: 'proyectoutem-d83cb',
    storageBucket: 'proyectoutem-d83cb.appspot.com',
    androidClientId: '517365773717-030mvm3mqotrfqpbqcaufllk6fjtjqj5.apps.googleusercontent.com',
    iosClientId: '517365773717-1f017vh3aqfdmjg8rml5rfhhrgccei1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoUtem',
  );

}